### ISSUE TITLE
WP Site doesn't include support for the Slide block

### ISSUE THREAD

**Issue by meaganhanes** [abstractwp/slide#2]
**Environment:** Vanilla WordPress 6.0.1 install with no other plugins. 

**Issue:** Upon entering the Presentation CPT editor, WordPress reports the following issue:

> Your site doesn’t include support for the Slide block. You can try installing the block, convert it to a Custom HTML block, or remove it entirely.

Clicking the "Install Slide" button results in this error message:

> Error registering block. Try reloading the page.

Reloading the page does not resolve this error.

**Comment by isvictorious** [comment]
@arlyons can you take a look at this issue with an FSE theme & without an FSE theme on a LocalWP instance? Document images for us to fix.

**Comment by arlyons** [comment]
@isvictorious @danhthong please see below. Not documented here but I had identical results with the non-FSE Twenty Twenty One theme.

**Screenshot:**
Add New Presentation:
https://a.cl.ly/WnuDKAzN

**Block Editor Error Message:**
https://a.cl.ly/E0uZ7P7v

**WP Admin Error message:**
https://a.cl.ly/z8uQ7wJg

**Steps to Reproduce:**
Upload “Presentation Block” plugin and activate
Click “Presentations” > “Add New”

**Context (Environment):**
- LocalWP Instance
- WP version: 6.01
- Theme: Twenty Twenty Two
- Browser: Chrome
- No other plugins installed

**Comment by danhthong** [comment]
@arlyons Please try to update new version of this plugin https://a.cl.ly/Kou1D7eK. If it's fixed, please let her know.

**Comment by arlyons** [comment]
@meaganhanes can confirm that @danhthong's fix worked. Please confirm when you can and thanks!

**Comment by meaganhanes** [comment]
Confirmed, plugin is working now. Off to the races we go! 🏇
